-- Admin-generated payroll cutoffs / payslips (visible on employee ESS after generate)

CREATE TABLE IF NOT EXISTS pcmazing_payroll_runs (
  id BIGSERIAL PRIMARY KEY,
  date_from DATE NOT NULL,
  date_to DATE NOT NULL,
  period_days INT NOT NULL,
  label VARCHAR(120) NOT NULL,
  generated_by_user_id BIGINT,
  generated_by_username VARCHAR(80),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_pcmazing_payroll_runs_period UNIQUE (date_from, date_to)
);

CREATE INDEX IF NOT EXISTS idx_pcmazing_payroll_runs_date_to
  ON pcmazing_payroll_runs (date_to DESC, id DESC);

CREATE TABLE IF NOT EXISTS pcmazing_generated_payslips (
  id BIGSERIAL PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES pcmazing_payroll_runs(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL,
  user_source VARCHAR(40) NOT NULL,
  username VARCHAR(80) NOT NULL,
  full_name VARCHAR(200) NOT NULL,
  employee_code VARCHAR(50),
  department VARCHAR(100),
  salary_type VARCHAR(30) NOT NULL,
  salary_amount NUMERIC(12, 2),
  days_present INT NOT NULL DEFAULT 0,
  days_completed INT NOT NULL DEFAULT 0,
  total_hours NUMERIC(10, 2) NOT NULL DEFAULT 0,
  estimated_pay NUMERIC(12, 2) NOT NULL DEFAULT 0,
  payroll_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_pcmazing_generated_payslips_run_user UNIQUE (run_id, user_id, user_source)
);

CREATE INDEX IF NOT EXISTS idx_pcmazing_generated_payslips_user
  ON pcmazing_generated_payslips (user_id, user_source, run_id DESC);

COMMENT ON TABLE pcmazing_payroll_runs IS
  'Payroll cutoff periods generated by admin; unlocks employee portal payslips.';

COMMENT ON TABLE pcmazing_generated_payslips IS
  'Frozen payslip rows for a generated payroll run (one per enrolled employee).';
